# Import Library

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import openpyxl

# Scrapping Website CoinMarketCap

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import openpyxl
def scappe(): 
    url = 'https://coinmarketcap.com/gainers-losers/'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    

    try:
        response = requests.get(url, headers=headers)
    except Exception as e:
        print(f"Koneksi gagal: {e}")
        return [], []
    
    if response.status_code != 200:
        print(f'Error: {response.status_code}')
        return [], []

    soup = BeautifulSoup(response.text, 'html.parser')
    
    tables = soup.findAll('table', class_='cmc-table')
    
    if len(tables) < 2:
        print("Tabel tidak ditemukan di halaman.")
        return [], []
    
    gainers_table = tables[0]
    losers_table = tables[1]
    
    def parse_table(target_table):
        data = []
        rows = target_table.findAll('tr')[1:]
        for row in rows:
            cols = row.findAll('td')
            if len(cols) >= 4:
                # Ambil teks koin dan bersihkan
                name = cols[1].text.strip()
                price = cols[2].text.strip()
                change_24h = cols[3].text.strip()
                volume_24h = cols[4].text.strip()
                
                data.append({
                    "Name": name,
                    "Price": price,
                    "24h Change": change_24h,
                    "Volume(24h)": volume_24h
                    
                })
        return data
    
    gainers_data = parse_table(gainers_table)
    losers_data = parse_table(losers_table)

    return gainers_data, losers_data    


gainers, losers = scappe()

if gainers or losers:
    print("--- TOP GAINERS ---")
    df_gainers = pd.DataFrame(gainers)
  
    df_gainers_excel = df_gainers.to_excel("gainers.xlsx")
    print(df_gainers.head(10))

    print("\n--- TOP LOSERS ---")
    df_losers = pd.DataFrame(losers)
    df_losers_excel = df_losers.to_excel("losers.xlsx")
    print(df_losers.head(10))
else:
    print("Tidak ada data yang berhasil diambil.")

C:\Users\Asus\AppData\Local\Temp\ipykernel_11216\2955714360.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  tables = soup.findAll('table', class_='cmc-table')
C:\Users\Asus\AppData\Local\Temp\ipykernel_11216\2955714360.py:35: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = target_table.findAll('tr')[1:]
C:\Users\Asus\AppData\Local\Temp\ipykernel_11216\2955714360.py:37: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  cols = row.findAll('td')

--- TOP GAINERS ---
                      Name     Price 24h Change   Volume(24h)
0               币安人生88币安人生   $0.4744     43.69%  $190,490,084
1            RaveDAO16RAVE    $25.40     40.87%  $339,060,748
2              MemeCore19M     $4.44     15.59%   $26,253,827
3               DeXe54DEXE    $13.13     12.23%   $32,136,735
4              Ethena55ENA    $0.123     11.60%  $269,728,278
5              edgeX87EDGE     $1.36     10.71%  $138,104,939
6  Aerodrome Finance99AERO   $0.4336      8.82%   $47,892,062
7           Morpho65MORPHO     $1.94      8.45%   $29,223,876
8                   Pi40PI   $0.1849      7.53%   $34,522,511
9                JUST77JST  $0.07022      7.41%   $42,730,397

--- TOP LOSERS ---
                                         Name     Price 24h Change  \
0                                siren83SIREN   $0.6868     64.36%
1                              Worldcoin62WLD   $0.2832     11.38%
2                              Algorand57ALGO   $0.1112      2.80%
3                                Toncoin30TON     $1.40      2.31%
4                       OFFICIAL TRUMP70TRUMP     $2.99      1.82%
5                           PancakeSwap82CAKE     $1.57      1.82%
6  Artificial Superintelligence Alliance81FET   $0.2285      1.45%
7                            XDC Network75XDC  $0.03091      1.09%
8                         NEAR Protocol42NEAR     $1.40      0.85%
9                              Render59RENDER     $1.85      0.76%

    Volume(24h)
0  $182,657,209
1  $296,720,581
2   $54,036,880
3  $157,693,802
4  $181,968,400
5   $62,025,270
6  $201,435,623
7   $25,930,784
8  $271,354,137
9  $106,035,372

# DataFrame Gainners Coin

In [3]:
gainners = pd.read_excel("gainers.xlsx")
dataframe_gainners = pd.DataFrame(gainners)
dataframe_gainners.head(10)

   Unnamed: 0                     Name     Price 24h Change   Volume(24h)
0           0               币安人生88币安人生   $0.4744     43.69%  $190,490,084
1           1            RaveDAO16RAVE    $25.40     40.87%  $339,060,748
2           2              MemeCore19M     $4.44     15.59%   $26,253,827
3           3               DeXe54DEXE    $13.13     12.23%   $32,136,735
4           4              Ethena55ENA    $0.123     11.60%  $269,728,278
5           5              edgeX87EDGE     $1.36     10.71%  $138,104,939
6           6  Aerodrome Finance99AERO   $0.4336      8.82%   $47,892,062
7           7           Morpho65MORPHO     $1.94      8.45%   $29,223,876
8           8                   Pi40PI   $0.1849      7.53%   $34,522,511
9           9                JUST77JST  $0.07022      7.41%   $42,730,397

# DataFrame Lossers Coin

In [4]:
loserss = pd.read_excel("losers.xlsx")
dataframe_losers = pd.DataFrame(loserss)
dataframe_losers.head(10)

,Unnamed: 0,Name,Price,24h Change,Volume(24h)
0,0,siren83SIREN,$0.6868,64.36%,"$182,657,209"
1,1,Worldcoin62WLD,$0.2832,11.38%,"$296,720,581"
2,2,Algorand57ALGO,$0.1112,2.80%,"$54,036,880"
3,3,Toncoin30TON,$1.40,2.31%,"$157,693,802"
4,4,OFFICIAL TRUMP70TRUMP,$2.99,1.82%,"$181,968,400"
5,5,PancakeSwap82CAKE,$1.57,1.82%,"$62,025,270"
6,6,Artificial Superintelligence Alliance81FET,$0.2285,1.45%,"$201,435,623"
7,7,XDC Network75XDC,$0.03091,1.09%,"$25,930,784"
8,8,NEAR Protocol42NEAR,$1.40,0.85%,"$271,354,137"
9,9,Render59RENDER,$1.85,0.76%,"$106,035,372"

# Check Missing Value Gainners

In [5]:
df_gainers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64

# Check Missing Value Lossers

In [6]:
df_losers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64

# Data Cleaning Gainners

In [7]:
df_gainers['Volume(24h)'] = df_gainers['Volume(24h)'].str.replace('$', '').str.replace(',', '').astype(float)
df_gainers['Price'] = df_gainers['Price'].str.replace('$', '').str.replace(',', '').astype(float)
df_gainers['24h Change'] = df_gainers['24h Change'].str.replace('%', '').astype(float)      


df_gainers

                          Name        Price  24h Change   Volume(24h)
0                   币安人生88币安人生      0.47440       43.69  1.904901e+08
1                RaveDAO16RAVE     25.40000       40.87  3.390607e+08
2                  MemeCore19M      4.44000       15.59  2.625383e+07
3                   DeXe54DEXE     13.13000       12.23  3.213674e+07
4                  Ethena55ENA      0.12300       11.60  2.697283e+08
5                  edgeX87EDGE      1.36000       10.71  1.381049e+08
6      Aerodrome Finance99AERO      0.43360        8.82  4.789206e+07
7               Morpho65MORPHO      1.94000        8.45  2.922388e+07
8                       Pi40PI      0.18490        7.53  3.452251e+07
9                    JUST77JST      0.07022        7.41  4.273040e+07
10                  Kaspa58KAS      0.03601        6.81  3.796075e+07
11             ether.fi92ETHFI      0.51220        6.35  4.802690e+07
12              Celestia100TIA      0.42430        6.07  1.055084e+08
13                Stellar18XLM      0.17450        4.73  1.549458e+08
14           Hyperliquid10HYPE     45.20000        4.29  3.169828e+08
15  Virtuals Protocol84VIRTUAL      0.75080        3.50  1.223296e+08
16                  Flare69FLR      0.00843        3.45  4.326587e+06
17                Ethereum2ETH   2403.22000        3.29  2.621523e+10
18                 Bitcoin1BTC  77004.25000        3.17  5.260151e+10
19                 Mantle37MNT      0.68250        2.60  4.608208e+07
20                     XRP4XRP      1.47000        2.48  3.990929e+09
21                Uniswap39UNI      3.44000        2.45  2.476908e+08
22             Midnight76NIGHT      0.03690        2.44  2.400893e+07
23               Polkadot38DOT      1.33000        2.42  2.516437e+08
24                  Monad95MON      0.03456        2.30  1.011566e+08
25                  Ondo52ONDO      0.26940        1.82  9.029062e+07
26                     BNB5BNB    640.79000        1.80  2.031349e+09
27                    Sky43SKY      0.07777        1.64  1.806011e+07
28           Venice Token98VVV      8.78000        1.54  2.360299e+07
29                Cosmos63ATOM      1.84000        1.53  6.627392e+07

# Data Cleaning Lossers

In [8]:
df_losers['Price'] = df_losers['Price'].str.replace('$', '').str.replace(',', '').astype(float)
df_losers['24h Change'] = df_losers['24h Change'].str.replace('%', '').astype(float)
df_losers['Volume(24h)'] = df_losers['Volume(24h)'].str.replace('$', '').str.replace(',', '').astype(float)

df_losers

,Name,Price,24h Change,Volume(24h)
0,siren83SIREN,0.686800,64.36,182657209.0
1,Worldcoin62WLD,0.283200,11.38,296720581.0
2,Algorand57ALGO,0.111200,2.80,54036880.0
3,Toncoin30TON,1.400000,2.31,157693802.0
4,OFFICIAL TRUMP70TRUMP,2.990000,1.82,181968400.0
5,PancakeSwap82CAKE,1.570000,1.82,62025270.0
6,Artificial Superintelligence Alliance81FET,0.228500,1.45,201435623.0
7,XDC Network75XDC,0.030910,1.09,25930784.0
8,NEAR Protocol42NEAR,1.400000,0.85,271354137.0
9,Render59RENDER,1.850000,0.76,106035372.0
10,VeChain73VET,0.007230,0.65,24048070.0
11,World Liberty Financial34WLFI,0.080600,0.61,104483874.0
12,Stacks90STX,0.239000,0.53,20055425.0
13,Bonk80BONK,0.056384,0.46,98350758.0
14,Filecoin68FIL,0.977500,0.43,157523183.0
15,Pepe46PEPE,0.053922,0.37,625382950.0
16,LayerZero74ZRO,1.950000,0.15,42576135.0
17,Aptos66APT,0.980400,0.08,104535125.0
18,Sei97SEI,0.057900,0.06,44771430.0

# Check Outlier Gainners

In [9]:
Q1 = df_gainers['Price'].quantile(0.25)
Q3 = df_gainers['Price'].quantile(0.75)
IQR = Q1 - Q3

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

qutlier_iqr = df_gainers[
    (df_gainers['Price'] < lower) | (df_gainers['Price'] > upper)
]

print('Jumlah outlier dari gainers: ', len(qutlier_iqr))

Jumlah outlier dari gainers:  30

# Check Outlier Lossers

In [10]:
Q1 = df_losers['Price'].quantile(0.25)
Q3 = df_losers['Price'].quantile(0.75)
IQR = Q1 - Q3

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

qutlier_iqr = df_losers[
    (df_losers['Price'] < lower) | (df_losers['Price'] > upper)
]

print('Jumlah outlier dari losers: ', len(qutlier_iqr))

Jumlah outlier dari losers:  19